version: "3.2"

services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27018:27017"
    environment:
      MONGODB_USERNAME: user1
      MONGODB_PASSWORD: password123
      MONGODB_DATABASE: test_db
    networks:
      - test

networks:
  test: